In [3]:
# CONECTAR GOOGLE DRIVE
from google.colab import drive
import pandas as pd

drive.mount('/content/drive')

# Ruta del archivo en tu Google Drive (ajusta según tu ubicación)
ruta_archivo = '/content/drive/MyDrive/miaad-nyc-r-s.csv'

# PRACTICA 13: CARGA DE DATOS
print("\n--- Práctica 13: Carga de Datos ---")
try:
    df = pd.read_csv(ruta_archivo, engine="python")  # Se eliminó skipfooter=1 por compatibilidad
    print("Archivo cargado correctamente.")
    print("Primeras 3 filas:\n", df.head(3))
except Exception as e:
    print(f"Error al cargar el archivo: {e}")

print("Últimas 3 filas (para verificar datos):\n", df.tail(3))
print("Dimensiones del dataframe (filas, columnas):", df.shape)

# PRACTICA 14: AGREGAR UNA COLUMNA
print("\n--- Práctica 14: Agregar una Columna ---")
print("Nombres originales de las columnas:\n", df.columns.tolist())

if df.columns[0].lower() != "index_miiad":
    df.rename(columns={df.columns[0]: "index_miiad"}, inplace=True)

df["nueva_columna"] = "valor_por_defecto"

print("Nombres corregidos de las columnas:\n", df.columns.tolist())

# PRACTICA 15: NORMALIZACIÓN DE NOMBRES DE COLUMNAS
print("\n--- Práctica 15: Normalización de Nombres de Columnas ---")
df.columns = df.columns.str.lower().str.replace(" ", "_", regex=True)
print("Nombres de columnas normalizados:\n", df.columns.tolist())

# PRACTICA 16: ERRORES EN TIPOS DE DATOS
print("\n--- Práctica 16: Errores en Tipos de Datos ---")
print("Tipos de datos antes de la conversión:\n", df.dtypes)

columnas_a_convertir = ["sale_price", "land_square_feet", "gross_square_feet"]
for col in columnas_a_convertir:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

print("Tipos de datos después de la conversión:\n", df.dtypes)

# PRACTICA 17: DICCIONARIO DE DATOS
print("\n--- Práctica 17: Diccionario de Datos ---")
diccionario_datos = {col: str(df[col].dtype) for col in df.columns}
print("Diccionario de datos:\n", diccionario_datos)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

--- Práctica 13: Carga de Datos ---
Archivo cargado correctamente.
Primeras 3 filas:
   Unnamed: 0  BOROUGH   NEIGHBORHOOD  \
0          4      1.0  ALPHABET CITY
1          5      1.0  ALPHABET CITY
2          6      1.0  ALPHABET CITY

                       BUILDING CLASS CATEGORY TAX CLASS AT PRESENT  BLOCK  \
0  07 RENTALS - WALKUP APARTMENTS                                2A  392.0
1  07 RENTALS - WALKUP APARTMENTS                                 2  399.0
2  07 RENTALS - WALKUP APARTMENTS                                 2  399.0

    LOT EASE-MENT BUILDING CLASS AT PRESENT                ADDRESS  ...  \
0   6.0                                  C2           153 AVENUE B  ...
1  26.0                                  C7  234 EAST 4TH   STREET  ...
2  39.0                                  C7  197 EAST 3RD   STREET  ...

  RESIDENTIAL UNITS  COMMERCIAL UNITS  TOTAL UNITS  LAND SQUARE FEET  \
0               5.0               0.0          5.0              1633
1              28.0               3.0         31.0              4616
2              16.0               1.0         17.0              2212

   GROSS SQUARE FEET YEAR BUILT TAX CLASS AT TIME OF SALE  \
0               6440     1900.0                       2.0
1              18690     1900.0                       2.0
2               7803     1900.0                       2.0

   BUILDING CLASS AT TIME OF SALE  SALE PRICE            SALE DATE
0                              C2     6625000  2017-07-19 00:00:00
1                              C7         -    2016-12-14 00:00:00
2                              C7         -    2016-12-09 00:00:00

[3 rows x 22 columns]
Últimas 3 filas (para verificar datos):
                                      Unnamed: 0  BOROUGH NEIGHBORHOOD  \
84546                                      8412      5.0      WOODROW
84547                                      8413      5.0      WOODROW
84548  Esta es una línea que no deberías cargar      NaN         None

                           BUILDING CLASS CATEGORY TAX CLASS AT PRESENT  \
84546  22 STORE BUILDINGS                                             4
84547  35 INDOOR PUBLIC AND CULTURAL FACILITIES                       4
84548                                         None                 None

        BLOCK    LOT EASE-MENT BUILDING CLASS AT PRESENT  \
84546  7100.0   28.0                                  K6
84547  7105.0  679.0                                  P9
84548     NaN    NaN      None                      None

                     ADDRESS  ... RESIDENTIAL UNITS  COMMERCIAL UNITS  \
84546  2730 ARTHUR KILL ROAD  ...               0.0               7.0
84547      155 CLAY PIT ROAD  ...               0.0               1.0
84548                   None  ...               NaN               NaN

       TOTAL UNITS  LAND SQUARE FEET  GROSS SQUARE FEET YEAR BUILT  \
84546          7.0            208033              64117     2001.0
84547          1.0             10796               2400     2006.0
84548          NaN              None               None        NaN

      TAX CLASS AT TIME OF SALE  BUILDING CLASS AT TIME OF SALE  SALE PRICE  \
84546                       4.0                              K6    11693337
84547                       4.0                              P9       69300
84548                       NaN                            None        None

                 SALE DATE
84546  2016-12-21 00:00:00
84547  2016-10-27 00:00:00
84548                 None

[3 rows x 22 columns]
Dimensiones del dataframe (filas, columnas): (84549, 22)

--- Práctica 14: Agregar una Columna ---
Nombres originales de las columnas:
 ['Unnamed: 0', 'BOROUGH', 'NEIGHBORHOOD', 'BUILDING CLASS CATEGORY', 'TAX CLASS AT PRESENT', 'BLOCK', 'LOT', 'EASE-MENT', 'BUILDING CLASS AT PRESENT', 'ADDRESS', 'APARTMENT NUMBER', 'ZIP CODE', 'RESIDENTIAL UNITS', 'COMMERCIAL UNITS', 'TOTAL UNITS', 'LAND SQUARE FEET', 'GROSS SQUARE FEET', 'YEAR BUILT', 'TAX CLASS AT TIME OF SALE', 'BUILDING CLASS AT TIME OF SALE', 'SALE PRICE', 'SALE DATE']
Nombres corregidos de las columnas:
 ['index_miiad', 'BOROUGH', 'NEIGHBORHOOD', 'BUILDING CLASS CATEGORY', 'TAX CLASS AT PRESENT', 'BLOCK', 'LOT', 'EASE-MENT', 'BUILDING CLASS AT PRESENT', 'ADDRESS', 'APARTMENT NUMBER', 'ZIP CODE', 'RESIDENTIAL UNITS', 'COMMERCIAL UNITS', 'TOTAL UNITS', 'LAND SQUARE FEET', 'GROSS SQUARE FEET', 'YEAR BUILT', 'TAX CLASS AT TIME OF SALE', 'BUILDING CLASS AT TIME OF SALE', 'SALE PRICE', 'SALE DATE', 'nueva_columna']

--- Práctica 15: Normalización de Nombres de Columnas ---
Nombres de columnas normalizados:
 ['index_miiad', 'borough', 'neighborhood', 'building_class_category', 'tax_class_at_present', 'block', 'lot', 'ease-ment', 'building_class_at_present', 'address', 'apartment_number', 'zip_code', 'residential_units', 'commercial_units', 'total_units', 'land_square_feet', 'gross_square_feet', 'year_built', 'tax_class_at_time_of_sale', 'building_class_at_time_of_sale', 'sale_price', 'sale_date', 'nueva_columna']

--- Práctica 16: Errores en Tipos de Datos ---
Tipos de datos antes de la conversión:
 index_miiad                        object
borough                           float64
neighborhood                       object
building_class_category            object
tax_class_at_present               object
block                             float64
lot                               float64
ease-ment                          object
building_class_at_present          object
address                            object
apartment_number                   object
zip_code                          float64
residential_units                 float64
commercial_units                  float64
total_units                       float64
land_square_feet                   object
gross_square_feet                  object
year_built                        float64
tax_class_at_time_of_sale         float64
building_class_at_time_of_sale     object
sale_price                         object
sale_date                          object
nueva_columna                      object
dtype: object
Tipos de datos después de la conversión:
 index_miiad                        object
borough                           float64
neighborhood                       object
building_class_category            object
tax_class_at_present               object
block                             float64
lot                               float64
ease-ment                          object
building_class_at_present          object
address                            object
apartment_number                   object
zip_code                          float64
residential_units                 float64
commercial_units                  float64
total_units                       float64
land_square_feet                  float64
gross_square_feet                 float64
year_built                        float64
tax_class_at_time_of_sale         float64
building_class_at_time_of_sale     object
sale_price                        float64
sale_date                          object
nueva_columna                      object
dtype: object

--- Práctica 17: Diccionario de Datos ---
Diccionario de datos:
 {'index_miiad': 'object', 'borough': 'float64', 'neighborhood': 'object', 'building_class_category': 'object', 'tax_class_at_present': 'object', 'block': 'float64', 'lot': 'float64', 'ease-ment': 'object', 'building_class_at_present': 'object', 'address': 'object', 'apartment_number': 'object', 'zip_code': 'float64', 'residential_units': 'float64', 'commercial_units': 'float64', 'total_units': 'float64', 'land_square_feet': 'float64', 'gross_square_feet': 'float64', 'year_built': 'float64', 'tax_class_at_time_of_sale': 'float64', 'building_class_at_time_of_sale': 'object', 'sale_price': 'float64', 'sale_date': 'object', 'nueva_columna': 'object'}