In [6]:
import pandas as pd
import os

# Montar Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Ruta del archivo en Drive (ajusta la ruta según corresponda)
file_path = '/content/drive/My Drive/miaad-nyc-r-s.csv'

# Verificar si el archivo existe antes de intentar cargarlo
if not os.path.exists(file_path):
    print(f"Error: El archivo no se encuentra en la ruta especificada: {file_path}")
    print("Verifica la ruta y asegúrate de que el archivo esté presente en tu Google Drive.")
else:
    # Práctica 13: Carga de Datos
    print("\nPráctica 13: Carga de Datos")
    # Cargar el archivo CSV omitiendo la última fila
    df = pd.read_csv(file_path, skipfooter=1, engine='python')

    # Mostrar las primeras filas para inspeccionar
    print(df.head())

    # Mostrar las últimas 3 filas para verificar que la última línea no se cargó
    print(df.tail(3))

    # Imprimir la cantidad de filas y columnas
    print("Filas y columnas:", df.shape)

    # Práctica 14: Agregar una columna
    print("\nPráctica 14: Agregar una columna")
    # Imprimir los nombres de las columnas
    print("Columnas antes de la corrección:", df.columns.tolist())

    # Asegurar el nombre de la primera columna
    df.rename(columns={df.columns[0]: 'INDEX MIIAD'}, inplace=True, errors='ignore')
    print("Columnas después de la corrección:", df.columns.tolist())

    # Práctica 15: Normalización de los nombres de las columnas
    print("\nPráctica 15: Normalización de los nombres de las columnas")
    # Convertir nombres a minúsculas y reemplazar espacios con guion bajo
    df.columns = df.columns.str.lower().str.replace(' ', '_', regex=True)
    print("Columnas normalizadas:")
    for col in df.columns:
        print("-", col)

    # Práctica 16: Errores en los Tipos de Datos
    print("\nPráctica 16: Errores en los Tipos de Datos")
    # Imprimir tipos de datos antes de la conversión
    print("Tipos de datos antes de la conversión:")
    print(df.dtypes)

    # Convertir columnas a tipo float si existen en el DataFrame
    columnas_a_convertir = ['sale_price', 'land_square_feet', 'gross_square_feet']
    for col in columnas_a_convertir:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors='coerce')

    # Imprimir tipos de datos después de la conversión
    print("Tipos de datos después de la conversión:")
    print(df.dtypes)

    # Validar cuántos valores NaN se generaron tras la conversión
    print("Valores faltantes tras la conversión:")
    print(df[columnas_a_convertir].isna().sum())

    # Práctica 17: Generar el diccionario de datos
    print("\nPráctica 17: Generar el diccionario de datos")
    data_dict = {col: str(df[col].dtype) for col in df.columns}
    print("Diccionario de datos del dataframe preprocesado:")
    print(data_dict)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Práctica 13: Carga de Datos
   Unnamed: 0  BOROUGH   NEIGHBORHOOD  \
0           4        1  ALPHABET CITY
1           5        1  ALPHABET CITY
2           6        1  ALPHABET CITY
3           7        1  ALPHABET CITY
4           8        1  ALPHABET CITY

                       BUILDING CLASS CATEGORY TAX CLASS AT PRESENT  BLOCK  \
0  07 RENTALS - WALKUP APARTMENTS                                2A    392
1  07 RENTALS - WALKUP APARTMENTS                                 2    399
2  07 RENTALS - WALKUP APARTMENTS                                 2    399
3  07 RENTALS - WALKUP APARTMENTS                                2B    402
4  07 RENTALS - WALKUP APARTMENTS                                2A    404

   LOT EASE-MENT BUILDING CLASS AT PRESENT                 ADDRESS  ...  \
0    6                                  C2            153 AVENUE B  ...
1   26                                  C7   234 EAST 4TH   STREET  ...
2   39                                  C7   197 EAST 3RD   STREET  ...
3   21                                  C4     154 EAST 7TH STREET  ...
4   55                                  C2  301 EAST 10TH   STREET  ...

  RESIDENTIAL UNITS  COMMERCIAL UNITS  TOTAL UNITS  LAND SQUARE FEET  \
0                 5                 0            5              1633
1                28                 3           31              4616
2                16                 1           17              2212
3                10                 0           10              2272
4                 6                 0            6              2369

   GROSS SQUARE FEET YEAR BUILT TAX CLASS AT TIME OF SALE  \
0               6440       1900                         2
1              18690       1900                         2
2               7803       1900                         2
3               6794       1913                         2
4               4615       1900                         2

   BUILDING CLASS AT TIME OF SALE  SALE PRICE            SALE DATE
0                              C2     6625000  2017-07-19 00:00:00
1                              C7         -    2016-12-14 00:00:00
2                              C7         -    2016-12-09 00:00:00
3                              C4     3936272  2016-09-23 00:00:00
4                              C2     8000000  2016-11-17 00:00:00

[5 rows x 22 columns]
       Unnamed: 0  BOROUGH NEIGHBORHOOD  \
84545        8411        5      WOODROW
84546        8412        5      WOODROW
84547        8413        5      WOODROW

                           BUILDING CLASS CATEGORY TAX CLASS AT PRESENT  \
84545  02 TWO FAMILY DWELLINGS                                        1
84546  22 STORE BUILDINGS                                             4
84547  35 INDOOR PUBLIC AND CULTURAL FACILITIES                       4

       BLOCK  LOT EASE-MENT BUILDING CLASS AT PRESENT                ADDRESS  \
84545   7351   60                                  B2       49 PITNEY AVENUE
84546   7100   28                                  K6  2730 ARTHUR KILL ROAD
84547   7105  679                                  P9      155 CLAY PIT ROAD

       ... RESIDENTIAL UNITS  COMMERCIAL UNITS  TOTAL UNITS  LAND SQUARE FEET  \
84545  ...                 2                 0            2              4000
84546  ...                 0                 7            7            208033
84547  ...                 0                 1            1             10796

       GROSS SQUARE FEET YEAR BUILT TAX CLASS AT TIME OF SALE  \
84545               1496       1925                         1
84546              64117       2001                         4
84547               2400       2006                         4

       BUILDING CLASS AT TIME OF SALE  SALE PRICE            SALE DATE
84545                              B2      460000  2017-07-05 00:00:00
84546                              K6    11693337  2016-12-21 00:00:00
84547                              P9       69300  2016-10-27 00:00:00

[3 rows x 22 columns]
Filas y columnas: (84548, 22)

Práctica 14: Agregar una columna
Columnas antes de la corrección: ['Unnamed: 0', 'BOROUGH', 'NEIGHBORHOOD', 'BUILDING CLASS CATEGORY', 'TAX CLASS AT PRESENT', 'BLOCK', 'LOT', 'EASE-MENT', 'BUILDING CLASS AT PRESENT', 'ADDRESS', 'APARTMENT NUMBER', 'ZIP CODE', 'RESIDENTIAL UNITS', 'COMMERCIAL UNITS', 'TOTAL UNITS', 'LAND SQUARE FEET', 'GROSS SQUARE FEET', 'YEAR BUILT', 'TAX CLASS AT TIME OF SALE', 'BUILDING CLASS AT TIME OF SALE', 'SALE PRICE', 'SALE DATE']
Columnas después de la corrección: ['INDEX MIIAD', 'BOROUGH', 'NEIGHBORHOOD', 'BUILDING CLASS CATEGORY', 'TAX CLASS AT PRESENT', 'BLOCK', 'LOT', 'EASE-MENT', 'BUILDING CLASS AT PRESENT', 'ADDRESS', 'APARTMENT NUMBER', 'ZIP CODE', 'RESIDENTIAL UNITS', 'COMMERCIAL UNITS', 'TOTAL UNITS', 'LAND SQUARE FEET', 'GROSS SQUARE FEET', 'YEAR BUILT', 'TAX CLASS AT TIME OF SALE', 'BUILDING CLASS AT TIME OF SALE', 'SALE PRICE', 'SALE DATE']

Práctica 15: Normalización de los nombres de las columnas
Columnas normalizadas:
- index_miiad
- borough
- neighborhood
- building_class_category
- tax_class_at_present
- block
- lot
- ease-ment
- building_class_at_present
- address
- apartment_number
- zip_code
- residential_units
- commercial_units
- total_units
- land_square_feet
- gross_square_feet
- year_built
- tax_class_at_time_of_sale
- building_class_at_time_of_sale
- sale_price
- sale_date

Práctica 16: Errores en los Tipos de Datos
Tipos de datos antes de la conversión:
index_miiad                        int64
borough                            int64
neighborhood                      object
building_class_category           object
tax_class_at_present              object
block                              int64
lot                                int64
ease-ment                         object
building_class_at_present         object
address                           object
apartment_number                  object
zip_code                           int64
residential_units                  int64
commercial_units                   int64
total_units                        int64
land_square_feet                  object
gross_square_feet                 object
year_built                         int64
tax_class_at_time_of_sale          int64
building_class_at_time_of_sale    object
sale_price                        object
sale_date                         object
dtype: object
Tipos de datos después de la conversión:
index_miiad                         int64
borough                             int64
neighborhood                       object
building_class_category            object
tax_class_at_present               object
block                               int64
lot                                 int64
ease-ment                          object
building_class_at_present          object
address                            object
apartment_number                   object
zip_code                            int64
residential_units                   int64
commercial_units                    int64
total_units                         int64
land_square_feet                  float64
gross_square_feet                 float64
year_built                          int64
tax_class_at_time_of_sale           int64
building_class_at_time_of_sale     object
sale_price                        float64
sale_date                          object
dtype: object
Valores faltantes tras la conversión:
sale_price           14561
land_square_feet     26252
gross_square_feet    27612
dtype: int64

Práctica 17: Generar el diccionario de datos
Diccionario de datos del dataframe preprocesado:
{'index_miiad': 'int64', 'borough': 'int64', 'neighborhood': 'object', 'building_class_category': 'object', 'tax_class_at_present': 'object', 'block': 'int64', 'lot': 'int64', 'ease-ment': 'object', 'building_class_at_present': 'object', 'address': 'object', 'apartment_number': 'object', 'zip_code': 'int64', 'residential_units': 'int64', 'commercial_units': 'int64', 'total_units': 'int64', 'land_square_feet': 'float64', 'gross_square_feet': 'float64', 'year_built': 'int64', 'tax_class_at_time_of_sale': 'int64', 'building_class_at_time_of_sale': 'object', 'sale_price': 'float64', 'sale_date': 'object'}